export const currencyOptions = [
  { label: "Euro (EUR)", value: "EUR" },
  { label: "US Dollar (USD)", value: "USD" },
  { label: "British Pound (GBP)", value: "GBP" },
  { label: "Lebanese Lira (LBP)", value: "LBP" },
  { label: "Saudi Riyal (SAR)", value: "SAR" },
  { label: "Qatari Riyal (QAR)", value: "QAR" },
  { label: "Kuwaiti Dinar (KWD)", value: "KWD" },
  { label: "Bahraini Dinar (BHD)", value: "BHD" },
  { label: "Omani Rial (OMR)", value: "OMR" },
  { label: "Jordanian Dinar (JOD)", value: "JOD" },
  { label: "Egyptian Pound (EGP)", value: "EGP" },
  { label: "Moroccan Dirham (MAD)", value: "MAD" },
  { label: "Tunisian Dinar (TND)", value: "TND" },
  { label: "Algerian Dinar (DZD)", value: "DZD" },
  { label: "Polish Zloty (PLN)", value: "PLN" },
  { label: "Swiss Franc (CHF)", value: "CHF" },
  { label: "Canadian Dollar (CAD)", value: "CAD" },
  { label: "Australian Dollar (AUD)", value: "AUD" },
  { label: "New Zealand Dollar (NZD)", value: "NZD" },
  { label: "Japanese Yen (JPY)", value: "JPY" },
  { label: "Chinese Yuan (CNY)", value: "CNY" },
  { label: "Hong Kong Dollar (HKD)", value: "HKD" },
  { label: "Singapore Dollar (SGD)", value: "SGD" },
  { label: "South Korean Won (KRW)", value: "KRW" },
  { label: "Thai Baht (THB)", value: "THB" },
  { label: "Malaysian Ringgit (MYR)", value: "MYR" },
  { label: "Indonesian Rupiah (IDR)", value: "IDR" },
  { label: "Philippine Peso (PHP)", value: "PHP" },
  { label: "Vietnamese Dong (VND)", value: "VND" },
  { label: "Swedish Krona (SEK)", value: "SEK" },
  { label: "Norwegian Krone (NOK)", value: "NOK" },
  { label: "Danish Krone (DKK)", value: "DKK" },
  { label: "Romanian Leu (RON)", value: "RON" },
  { label: "Bulgarian Lev (BGN)", value: "BGN" },
  { label: "Bosnia and Herzegovina Mark (BAM)", value: "BAM" },
  { label: "Serbian Dinar (RSD)", value: "RSD" },
  { label: "Czech Koruna (CZK)", value: "CZK" },
  { label: "Hungarian Forint (HUF)", value: "HUF" },
  { label: "Croatian Kuna (HRK)", value: "HRK" },
  { label: "North Macedonian Denar (MKD)", value: "MKD" },
  { label: "Albanian Lek (ALL)", value: "ALL" },
  { label: "Ukrainian Hryvnia (UAH)", value: "UAH" },
  { label: "Turkish Lira (TRY)", value: "TRY" },
  { label: "Indian Rupee (INR)", value: "INR" },
  { label: "UAE Dirham (AED)", value: "AED" },
  { label: "South African Rand (ZAR)", value: "ZAR" },
  { label: "Mexican Peso (MXN)", value: "MXN" },
  { label: "Brazilian Real (BRL)", value: "BRL" },
  { label: "Argentine Peso (ARS)", value: "ARS" },
  { label: "Chilean Peso (CLP)", value: "CLP" },
  { label: "Colombian Peso (COP)", value: "COP" },
];
